### PR TITLE
Missing query params

### LINKED ISSUE #134: [universal-redux] Router doesn't accept query params
This happens if I reload current page if I navigate in loaded application, problem doesn't appear.
What I see in console:
```
console.log(location)
console.log(renderProps.location)
```
```
admin/categories?_limit=100
{ pathname: 'admin/categories',
   search: '',
   hash: '',
   state: undefined,
   action: 'POP',
   key: '859a8w',
   basename: '/',
   query: {} }
 GET /admin/categories?_limit=100 200 223.067 ms - -
```

### PR DESCRIPTION
**Pull request by kybarg**
fix #134

### CODE REVIEW

**Comment by diegohaz** [comment]
@kybarg We need the `basename` config so we can use `PUBLIC_PATH=foo npm run build` to create bundle to run on url paths other than root.

Please, see my answer to this question on StackOverflow: http://stackoverflow.com/questions/40528489/use-basename-in-react-router-on-server-side

Does it work?
```js
const history = createMemoryHistory({ entries: [location], basename })
```

**Comment by diegohaz** [comment]
Also, as I understood from your issue, this is a problem with server, not client. Is the `client.js` change necessary?

**Comment by kybarg** [comment]
```javascript
const history = createMemoryHistory({ entries: [location], basename })
```
This works for client but not server

**Comment by kybarg** [comment]
@diegohaz I've updated PR

**Comment by diegohaz** [comment]
Thank you, @kybarg. Will review that asap.

**Comment by kybarg** [comment]
@diegohaz Yes, you are right. I've double checked and now everything works. I guess that bug appeared at my fork cause of outdated packages or smth 😄

**Pull request closed without merging**
