### PR TITLE
Add Storyshots - Closes #96

### LINKED ISSUE #96: Add storyshots
Storyshots are basically Jest Snapshots to test  Storybook. https://github.com/storybooks/storyshots

### PR DESCRIPTION
**Pull request by abhishekisnot**
**What does this PR addresses ?**

- [x] Rename ``test`` directory to ``__test__`` which aligns more with what Jest expects. The jest snapshot directory then is ``__test__/__snapshots__``
- [x] Change storybook config to use require.context based on relative path (vs webpack resolved path) - storyshots currently errors out on webpack resolved path in context
- [x] Mark *.lock as binary files which skips diffs on yarn.lock file in PRs

**What would this PR change ?**

**Tests** BEFORE:
screen shot 2017-02-15 at 12 46 12 am
**Tests** AFTER:
screen shot 2017-02-15 at 12 46 25 am

**Coverage** BEFORE:
screen shot 2017-02-15 at 12 59 59 am
**Coverage** AFTER:
screen shot 2017-02-15 at 1 00 09 am

### CODE REVIEW

**Comment by diegohaz** [comment]
Thank you very much for your work, @abhishekisnot. Now we have a good view of what it would look like with `storyshots`.

The problem is everything we add to the boilerplate is one more thing for new developers to figure out. And, honestly, analyzing the snapshots, I don't think it's worth it. Most of them are just `span`s because we are mocking components in [`test/componentsMock.js`](https://github.com/diegohaz/arc/blob/master/test/componentsMock.js) to ensure isolated unit tests.

**Comment by diegohaz** [comment]
I didn't know about the `yarn.lock` trick though. Merging it is always really annoying 😆. 

Can you put that in a separate PR?

**Comment by abhishekisnot** [comment]
Yeah, from value proposition, this makes sense. Thank you for considering the feature.

**Comment by abhishekisnot** [comment]
Just a sidenote, if we do not mock the component for tests, I start getting errors on Jest tests as:
> `` TypeError: require.context is not a function ``

It seems, Jest does not/won't support dynamic requires as mentioned here:
https://github.com/facebookincubator/create-react-app/issues/517
https://github.com/facebook/jest/issues/2298

**Comment by diegohaz** [comment]
Yeah, Jest doesn't support that. And that's another reason to mock components.

I agree with Dan. `require.context` is  kinda obscure, but it really improves developer experience, especially in our case (can use Atomic Design structure without pain).

Anyway, thank you, @abhishekisnot. I'll close this PR, but I think it's still valuable as a reference for one wanting to add this feature to their projects.

**Pull request closed without merging**
