### PR TITLE
Updating all dependencies, with tests

### PR DESCRIPTION
**Pull request by BrenoMazieiro**
Like @kybarg 
# Highlights
* Updated webpack to version 4
* Removed webpack-blocks dependency in favor of plain config file
* Updated babel
* Dropped support for Node.js 6
* Removed unused dependencies

Plus
* react:  16.8.5
* react-dom:  16.8.5
* react-router-dom: 5.0.0
* react-redux: 6.0.1
* redux: 4.0.1
* redux-form 8.1.0
* redux-saga: 1.0.2
* redux-saga-thunk: 0.7.3
* styled-components: 4.2.0
* and more...

### CODE REVIEW

**Comment by BrenoMazieiro** [comment]
Well, that is it!
Every package is updated!
Coverage at 99%

BUT

Things I was not able to do:

1-) When running the test I've got warnings like: 
It looks like you've wrapped styled() around your React component (Icon), but the classNa
me prop is not being passed down to a child. No styles will be rendered unless className is com
posed within your React component.

2-) At console Browser there is a warning:
React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

3-) When update storybook/react and storybook/addon-actions to 5.0.5:
Ive got a error running "yarn storybook:example"
Something about the webpack.config file inside private folder.

anyone willing to help me?
Thanks guys!

**Comment by BrenoMazieiro** [comment]
> Like @kybarg
> 
> # Highlights
> * Updated webpack to version 4
> * Removed webpack-blocks dependency in favor of plain config file
> * Updated babel
> * Dropped support for Node.js 6
> * Removed unused dependencies
> 
> Plus
> 
> * react:  16.8.5
> * react-dom:  16.8.5
> * react-router-dom: 5.0.0
> * react-redux: 6.0.1
> * redux: 4.0.1
> * redux-form 8.1.0
> * redux-saga: 1.0.2
> * redux-saga-thunk: 0.7.3
> * styled-components: 4.2.0
> * and more...

**Comment by gfsd3v** [comment]
> Well, that is it!
> Every package is updated!
> Coverage at 99%
> 
> BUT
> 
> Things I was not able to do:
> 
> 1-) When running the test I've got warnings like:
> It looks like you've wrapped styled() around your React component (Icon), but the classNa
> me prop is not being passed down to a child. No styles will be rendered unless className is com
> posed within your React component.
> 
> 2-) At console Browser there is a warning:
> React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
> 
> 3-) When update storybook/react and storybook/addon-actions to 5.0.5:
> Ive got a error running "yarn storybook:example"
> Something about the webpack.config file inside private folder.
> 
> anyone willing to help me?
> Thanks guys!

I'm also having problems with the storybook thing, but what u did would really be helpful, someone should review and release this PR.

**Comment by kybarg** [comment]
@BrenoMazieiro Thank you for you contribution, going to check this PR over the weekend.

**Comment by gfsd3v** [comment]
Hey @BrenoMazieiro, I was able to fix the webpack configuration for the storybook update, don't know if I should wait for this PR to be released to open my PR or if I should just do it now, what are u thoughts on it ?

**Comment by BrenoMazieiro** [comment]
I believe it depends, if you made it from my PR, you should wait, because it may be that soon we will have an answer on mine. If you made from redux branch, then open a PR.
Anyway I'm curious to know how it solved the problem!

**Comment by BrenoMazieiro** [comment]
Maybe @diegohaz or @kybarg can help us with it!

**Comment by diegohaz** [comment]
@gfsd3v if your PR is based on @BrenoMazieiro's branch, you can open a new PR with his commits included.

**Comment by BrenoMazieiro** [comment]
@gfsd3v do you mind to explain/share how you solved the problem with storybook?

**Comment by BrenoMazieiro** [comment]
@gfsd3v and @diegohaz, updated, all errors and warnings is now ok, and storybook it is in its last version.

**Comment by kybarg** [comment]
@diegohaz everything looks perfect so far

**Comment by diegohaz** [comment]
Thank you for the awesome work, @BrenoMazieiro (sent you an invitation to be collaborator on this project)! And thank you @kybarg for reviewing this! ❤️

**Comment by EricWVGG** [comment]
Is anyone actively working on the Redux-SSR branch?

**Comment by diegohaz** [comment]
@EricWVGG Not that I’m aware of

**Pull request merged**
