### PR TITLE
Upgrade react to 15.5.x

### PR DESCRIPTION
**Pull request by kybarg**
Some related packages aren't upgraded yet
1. https://github.com/styled-components/styled-components/pull/683
2. https://github.com/commissure/redbox-react/pull/88
3. https://github.com/reactjs/react-modal/pull/374
4. https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/88

### CODE REVIEW

**Comment by diegohaz** [comment]
Awesome. Is there a way to not include `prop-types` package in production? Since we use `babel-plugin-transform-react-remove-prop-types` (https://github.com/diegohaz/arc/blob/master/.babelrc#L25)

**Comment by kybarg** [comment]
@diegohaz you're right, I will investigate it now.

**Comment by kybarg** [comment]
@diegohaz it looks like PR was made to https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types but not released yet.

**Comment by diegohaz** [comment]
#213 produced a bunch of conflicts on this. But they are automatically solved with `git merge`. I did that, but this PR doesn't allow edit from authors :(

**Comment by kybarg** [comment]
@diegohaz nice 👍

**Pull request merged**
