### PR TITLE
[fullstack] upgraded mockgoose and getting past 74 tests but failing …

### PR DESCRIPTION
**Pull request by protoEvangelion**
…the src/api/post/model.test.js suite if you could help me make it all the way I would really appreciate it 👍

### CODE REVIEW

**Comment by diegohaz** [comment]
Thank you, @protoEvangelion. I'm investigating it right now.

**Comment by diegohaz** [comment]
I made some changes (cff8c470f357d5e22151a66f86b094d9fd232fa4) on your code and everything passes now, but some process (probably related to mockgoose) is still running, thus tests don't finish. :/

**Comment by diegohaz** [comment]
Using Jest's `--forceExit` did the job. 🎉

Could you please check if it works on Windows?

**Comment by protoEvangelion** [comment]
Victory!  Thanks Diego!  The tests actually run faster now as well 🥇

**Pull request merged**
